server:
  port: 3000
db:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 12344
  database: cmplus_qa
  maxConnections: 100
milvus:
  host: 170.18.9.106:29530
  username: root
  password: ehncf2000
  dbname: cmplus_qa
nats:
  endpoint: nats://1.94.184.24:4222
  subject: "sudy.ai.req.{clientId}.bizCall.cmqa.>"
  streamName: "cmqa_stream"
  articleSubject: "sudy.ai.req.{clientId}.bizCall.cmqa.article"
  articleConsumerName: "cmqa_article_consumer"
  imagesProcSubject: "sudy.ai.notify.{ClientID}.imagesProc.preProcess"
  imagesProcConsumerName: "cm_ai_images_proc_consumer"
  clientId: "dreamertest-sudy"
  defaultAccountName: cm
  account:
    cm:
      username:
      password:
      seed: "SUAG5FS7H253CMJBZFATMT4E4CLPA22AX37DBUAGF3JPK4EJ7TQ7LBQ4LM"
      nkey: "UBUGBPDHPW44AA4I6YNUDJ4GFRSMNJFNMU64BMBJTQDXLLACII5CSXTP"


